(define (memq-custom item x)
  (cond ((null? x) #f)
		((eq? (car x) item) x)
		(else (memq-custom item (cdr x)))
		 ))

(display (memq-custom 2 (list 1 2 3 4)))
(newline)
(display (memq-custom 5 (list 1 2 3 4)))
(newline)
(display (memq-custom 'apple '(prune pear banana)))
(newline)
(display (memq-custom 'apple '(x (apple sauce) y apple pear)))
(newline)
