(define x (list 1 2 (list 3 4 (list 5 6 (list 7 8)))))

(define (first-leaf tree)
 (if (not (pair? tree))
	 tree
	 (first-leaf (car tree))))
(define (exclude-first-leaf tree)
 (if (not (pair? (car tree)))
	 (cdr tree)
	 (append (exclude-first-leaf (car tree)) (cdr tree))))

(define (fringe tree)
 (if(null? tree)
   ()
   (cons (first-leaf tree) (fringe (exclude-first-leaf tree)))))
(display x)
(newline)
(display (first-leaf x))
(newline)
(display (exclude-first-leaf x))
(newline)
(display (fringe x))
(newline)
