(define (make-account balance)
 (define (withdraw amount)
   (if (>= balance amount)
	   (begin (set! balance (- balance amount))
			  balance)
	   "Insufficient funds"))
 (define (deposit amount)
   (set! balance (+ balance amount))
   balance)
 (define (dispatch m)
  (cond ((eq? m 'withdraw) withdraw)
		((eq? m 'deposit) deposit)
		(else (error "Unknown request -- MAKE-ACCOUNT" m))))
 dispatch
 )

(define A1 (make-account 100))
(newline)
(display ((A1 'withdraw) 20))
(newline)
(display ((A1 'deposit) 30))
(newline)
