(define (count-pairs x)
 (if (not (pair? x))
	 0
	 (begin
	  (+ (count-pairs (car x))
		(count-pairs (cdr x))
		1))))

(define c (cons 2 ()))
(define b (cons 1 c))
(define a (append b b))
(define x (cons c c))
(define y (cons x x))

(newline)
(display a)
(newline)
(display b)
(newline)
(display c)
(newline)
(display x)
(newline)
(display y)
(newline)
(display (count-pairs a))
(newline)
(display (count-pairs (list 1 2 3)))
(newline)
(display (count-pairs y))
